### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by xs4u** [IITPP-Roblox/Unified-3D-Input#2]
`require(game:GetService("ReplicatedStorage"):WaitForChild("Unified3DInput")):SetUpClient()` - this is wrong
`require(game:GetService("ReplicatedStorage"):WaitForChild("Unified3DInput")).SetUpClient()` - this is correct
(the : is actually an . from what I see in the code of module)

**Comment by TheNexusAvenger** [comment]
With the current code, both are fine. I cover what `.` vs `:` is in an older post on the DevForum.
https://devforum.roblox.com/t/oop-using-self/282376/2
